#!/bin/sh

#
# Sim2L
#
/usr/bin/invoke_app "$@" -t gitlocalsimtool \
                         -C "start_jupyter -T @tool -t gitlocalsimtoolExample.ipynb" \
                         -u anaconda-X \
                         -r none \
                         -w headless
